### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Fxyer** [chinasun021/pwd_crack#1]
兄弟，这个报错怎么解决呢？Copying pycparser-2.14-py2.7.egg to /private/var/folders/rt/3r2zlx6n4d158p3rk_cgw3xw0000gn/T/easy_install-aPjdOJ/cryptography-1.4/.eggs

Installed /private/var/folders/rt/3r2zlx6n4d158p3rk_cgw3xw0000gn/T/easy_install-aPjdOJ/cryptography-1.4/.eggs/pycparser-2.14-py2.7.egg
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*' found under directory 'vectors'
build/temp.macosx-10.6-x86_64-2.7/_openssl.c:423:10: fatal error: 'openssl/opensslv.h' file not found
# include <openssl/opensslv.h>

```
     ^
```

1 error generated.
error: Setup script exited with error: command 'gcc' failed with exit status 1

**Comment by chinasun021** [comment]
应该是有软件没安装，可以尝试：
sudo apt-get install python-dev

**Comment by Fxyer** [comment]
可是我的是MAC本本，我应该怎么安装python-dev呢？我之前就是brew install python安装的python呢！谢谢！

**Comment by chinasun021** [comment]
参考下http://stackoverflow.com/questions/6906385/mac-osx-lion-virtualenv-pil-install-gcc-error
MAC我也没试过，不行就虚拟机吧

**Comment by Fxyer** [comment]
恩，我先看看，因为自己的是MAC，有一个windows的虚拟机，既然有MAC了就不想安装*nix的虚拟机了，不然Metasploit也可以用来暴力破解ssh的，但是安装个Meta感觉好臃肿啊，兄弟谢谢啊
